### ISSUE TITLE
how can I search in React native jobs?

### ISSUE THREAD

**Issue by peyman-hakemi** [ManiMozaffar/linkedIn-scraper#11]
how can I search in React native jobs in the bot?

**Comment by ManiMozaffar** [comment]
Hi peyman,
there's no react native included in keywords, I'll include them ASAP with next push.

You can see all keywords from /info in bot, or from the following URL:
https://github.com/ManiMozaffar/linkedIn-scraper/blob/main/src/services/tech/loaddata.py

to filter a namespace, you need to write a logical expression like this:
```python
react_native and remote
```

this will filter and sends you jobs that are react and they're remote.

**Comment by ManiMozaffar** [comment]
#13 

Hello , react native is now supported :-)
Cheers!
