### ISSUE TITLE
Am i doing something wrong? for entering query

### ISSUE THREAD

**Issue by peyman-hakemi** [ManiMozaffar/linkedIn-scraper#12]
![image](https://user-images.githubusercontent.com/38393852/234201091-5a15f02d-7281-45e2-a4b2-5c4859043f0a.png)

I'm typing "react and netherlands"
and when I want to see my query it says "No Query Found"

am I doing something wrong?

**Comment by ManiMozaffar** [comment]
> ![image](https://user-images.githubusercontent.com/38393852/234201091-5a15f02d-7281-45e2-a4b2-5c4859043f0a.png)
> 
> I'm typing "react and netherlands" and when I want to see my query it says "No Query Found"
> 
> am I doing something wrong?

Hi , I'll investigate this issue, just wondering if you're joined in the channel? if not, then that's probably why but bot should have warned you about this.
Your query is probably fine .

**Comment by ManiMozaffar** [comment]
#13 Fixed this issue, thanks for reporting!

Cheers :)

**Comment by mohsenasm** [comment]
Hi @ManiMozaffar 
This bug still exists.
<img width="479" alt="Screen Shot 2023-04-29 at 12 00 56 PM" src="https://user-images.githubusercontent.com/9164422/235293280-871125ba-de82-45ef-9df4-0f1fee5440e0.png">

**Comment by ManiMozaffar** [comment]
Hi, thanks for addressing the issue again,
I have fixed it and assigned you "go or python or docker", and it worked fine. 
this filter is too general, it can attracts any kind of devops/other field job as well, make sure to wrap it up with "backend" or more detailed filters!

I'd have to write some tests using my own telegram ID to ensure the integration!
