### ISSUE TITLE
Telegram channel status ? (@linkedin_python)

### ISSUE THREAD

**Issue by WatchDogsDev** [ManiMozaffar/linkedIn-scraper#18]
Hi, Thanks for your great work. 

I want to ask why is your channel stopped working ?

**Comment by ManiMozaffar** [comment]
Hey,
Crawlers go back alive today,
I needed to refactor things, and move source code to a server, my PC can rest at nights.
In the refactored version, as I'm running tests now, we've 15x scaled in speed :)

**Comment by WatchDogsDev** [comment]
Nice! Thanks

Please add a donation way to support the project costs. (Something like Tron crypto wallet)

**Comment by ManiMozaffar** [comment]
Service is running now!

Sure thing, I'll add it to readme tomorrow ;)
